#!/bin/bash
### Usage: sagwassi [<option>*]
###
### where <option> is one of:
###   ansible_flags=<csv>      Run ansible with flags in <csv>
###                            Example: ansible_flags=--step,--version
###                            Default: ansible_flags=--ask-become-pass,-vv
###   ansible_skip_tags=<csv>  Make ansible skip tasks that are marked with tags contained in <csv>
###                            Example: ansible_skip_tags=debug,sagwassi
###   ansible_tags=<csv>       Make ansible only run tasks that are marked with tags contained in <csv>
###                            Example: ansible_tags=debug,sagwassi
###   git_branch=<branch>      Set remote git branch of sagwassi to <branch>
###   git_url=<url>            Set remote git repository of sagwassi to <url>
###   home=<path>              Run ansible with <path> as home directory
###   sagwassi_dir=<path>      Set the base dir of sagwassi to <path>
###   sagwassi_mode=local      Do not pull latest sagwassi updates from repository
###   sagwassi_reinstall=true  Remove existing installation and reinstall sagwassi
###   sagwassi_sh=<path>       Use sagwassi script from <path> if sagwassi must restart itself
###   ssh_key=<path>           Use SSH key from <path>
###   user=<name>              Run as user <name>

set -e

help() {
  awk -F'### ' '/^###/ { print $2 }' "$0"
}

if [[ "$1" == "-h" ]]; then
  help "$@"
  exit 0
fi

all_args=${all_args:-$@}

if ! xcode-select -v 2>/dev/null ; then
  echo "installing xcode commandline tools ..."
  xcode-select --install 2>/dev/null || true
fi

if [ ! -x /usr/local/bin/brew ]; then
  echo "installing homebrew ..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

export PATH=/usr/local/bin:$PATH

if [ ! -x /usr/local/bin/git ]; then
  echo "installing git ..."
  brew install git
fi

if [ ! -x /usr/local/bin/ansible ]; then
  brew install ansible
else
  HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade ansible
fi

if [ ! -x /usr/local/bin/jq ]; then
  brew install jq
fi

python_version=$(brew info ansible --json | jq '[.[] | .dependencies]' | grep python | head -1 | tr -d '[:blank:]' | tr -d \")
python_path="/usr/local/opt/$python_version/bin"
ansible_python_interpreter="$python_path/python3"

# parse command line arguments
for ARGUMENT in $all_args; do

  KEY=$(echo "$ARGUMENT" | cut -f1 -d=)
  VALUE=$(echo "$ARGUMENT" | cut -f2 -d=)

  case "$KEY" in
  home) home=${VALUE} ;;
  sagwassi_dir) sagwassi_dir=${VALUE} ;;
  sagwassi_mode) sagwassi_mode=${VALUE} ;;
  sagwassi_reinstall) sagwassi_reinstall=${VALUE} ;;
  sagwassi_sh) sagwassi_sh=${VALUE} ;;
  ansible_flags) ansible_flags=${VALUE} ;;
  ansible_skip_tags) ansible_skip_tags=${VALUE} ;;
  ansible_tags) ansible_tags=${VALUE} ;;
  git_url) git_url=${VALUE} ;;
  git_branch) git_branch=${VALUE} ;;
  ssh_key) ssh_key=${VALUE} ;;
  user) user=${VALUE} ;;
  *) ;;
  esac
done

sagwassi_dir=${sagwassi_dir:-$HOME/.sagwassi}
sagwassi_properties="$sagwassi_dir/sagwassi.properties"

# read from sagwassi.properties
if [ -f "$sagwassi_properties" ] && [ -z ${sagwassi_reinstall+x} ]; then # ignore SC2154
  while read -r LINE; do
    KEY=$(echo "$LINE" | cut -f1 -d=)
    VALUE=$(echo "$LINE" | cut -f2 -d=)

    case "$KEY" in
    git_url) git_url=${git_url:-$VALUE} ;;
    git_branch) git_branch=${git_branch:-$VALUE} ;;
    home) home=${home:-$VALUE} ;;
    ssh_key) ssh_key=${ssh_key:-$VALUE} ;;
    user) user=${user:-$VALUE} ;;
    *) ;;
    esac
  done <"$sagwassi_properties"
else # reinstall sagwassi
  mv "$sagwassi_dir" "/tmp/sagwassi_delete_me_$(base64 </dev/urandom | tr -dc 'a-zA-Z0-9' | head -c20)" 2>/dev/null || true
  echo "Reinstalling sagwassi ..."
fi

# ensure at least default values
home=${home:-$HOME}
user=${user:-$USER}
sagwassi_sh=${sagwassi_sh:-"$0"}
ansible_flags=${ansible_flags:-"--ask-become-pass,-vv"}
ansible_tags=${ansible_tags:-all}

# ssh setup for git
ssh_status=0
ssh-add -l &>/dev/null || ssh_status="$?"
if [ "$ssh_status" -eq 2 ] && [ -z ${ssh_agent_subprocess+x} ]; then # ignore SC2154
  echo "Starting ssh-agent"
  exec /usr/bin/ssh-agent "$sagwassi_sh" "$all_args" "ssh_agent_subprocess=true"
else
  [ "$ssh_status" -gt 0 ] && ssh-add ${ssh_key:+"$ssh_key"} && ssh_status="$?"
  [ "$ssh_status" -gt 0 ] && {
    echo "There is a problem with your ssh keys, sagwassi does not know how to fix that and exits. You could try to set the path to your ssh-key explicitly by via the corresponding command line argument or by editing the sagwassi.properties file. Call 'sagwassi -h' if you want to know how to do that."
    exit $ssh_status
  }

  # ensure vars via prompt
  if [ -z ${git_url+x} ]; then
    read -rp 'sagwassi git url (default: https://github.com/lomin/sagwassi.git): ' git_url
    git_url=${git_url:-https://github.com/lomin/sagwassi.git}
  fi

  if [ -z ${git_branch+x} ]; then
    read -rp 'sagwassi git branch (default: master): ' git_branch
    git_branch=${git_branch:-master}
  fi

  # clone sagwassi if not already there and save git vars
  if [ ! -f "$sagwassi_properties" ]; then
    git clone "$git_url" "$sagwassi_dir"
    echo git_url="$git_url" >>"$sagwassi_properties"
    echo git_branch="$git_branch" >>"$sagwassi_properties"
  fi

  if [ "$sagwassi_mode" = local ]; then
    echo sagwassi is in local mode
  else
    git -C "$sagwassi_dir" fetch
    git -C "$sagwassi_dir" checkout "$git_branch"
    git -C "$sagwassi_dir" pull
  fi
  read -ra ansible_flags_array < <(echo "$ansible_flags" | tr , " ")
  (cd "$sagwassi_dir" && exec ansible-playbook "${ansible_flags_array[@]}" -i "$sagwassi_dir/hosts.yml" "$sagwassi_dir/site.yml" --extra-vars "$all_args sagwassi_dir=$sagwassi_dir sagwassi_sh=$sagwassi_sh home=$home user=$user python_version=$python_version python_path=$python_path ansible_python_interpreter=$ansible_python_interpreter" --tags="$ansible_tags" --skip-tags="$ansible_skip_tags")
fi
