---
- name: install intel-mkl
  apt:
    name: intel-mkl
    update_cache: yes
    cache_valid_time: 0
    state: present
  become: yes
  tags: [ mkl, dlfp ]

- name: copy start.sh
  copy:
    src: files/start.sh
    dest: "/vagrant/start.sh"
    owner: "{{ user }}"
    mode: 0744
    force: yes
  tags: [ dlfp ]