---
- name: Enable multiverse repository
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ jammy multiverse"
    - "deb http://archive.ubuntu.com/ubuntu/ jammy-updates multiverse"
    - "deb http://security.ubuntu.com/ubuntu/ jammy-security multiverse"
    
- name: install intel-mkl
  apt:
    name: intel-mkl
    update_cache: yes
    cache_valid_time: 0
    state: present
  become: yes
  tags: [ mkl, dlfp ]

- name: copy start.sh
  template:
    src: start.sh
    dest: "{{ home }}/start.sh"
    owner: "{{ user }}"
    mode: 0744
    force: yes
  tags: [ dlfp ]
